name       : gtkspellmm
version    : 3.0.5
release    : 5
source     :
    - http://iweb.dl.sourceforge.net/project/gtkspell/gtkspellmm/gtkspellmm-3.0.5.tar.xz : 5b875a5753ce593274d0c6e803af6300973020c5443905999aba96ed3cef1545
license    : GPL-2.0-only
component  : desktop.library
summary    : gtkspellmm is the C++ binding for the gtkspell3 library
description: |
    gtkspellmm is the C++ binding for the gtkspell3 library
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtkspell3-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
